name: Generate docsets

on:
  push:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: 'false'

jobs:
  docsets:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: "Clone Repo"
        run: |
          git clone https://github.com/psf/requests.git
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "requests/docs/"
          pre-build-command: "pip install requests guzzle_sphinx_theme"
      - name: "Install dependencies"
        run: |
          pip install Sphinx==3.5.4 guzzle_sphinx_theme doc2dash
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      - name: "Build docs"
        run: cd requests/docs && doc2dash _build/html/ --name requests --destination ~/.
      - name: "Commit docsets"
        run: |
          git config --global user.email "docsets-bot@example.com"
          git config --global user.name "docsets-bot"
          git add requests.docset && git commit -m "Updated docsets"
          git push