on:
  push:
    branches: ["master"]

jobs:
  docsets:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "python3.9"
      - name: "Install dependencies"
        run: ./boto3.sh