on:
  push:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

jobs:
  docsets:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: "Clone Repo"
        run: |
          git clone https://github.com/boto/boto3.git
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "boto3/docs/"
          pre-build-command: "pip install boto3 guzzle_sphinx_theme"
      - name: "Install dependencies"
        run: |
          pip install doc2dash
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      - name: "Build docs"
        run: cd boto3/docs && doc2dash docs/_build/html/ --name boto3 --destination ./boto3-docs